repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.3
  hooks:
    # Run the linter
    - id: ruff-check
      types_or: [python, pyi]
      args: [--fix, '--exclude', 'tests/*']  # Skip the tests directory

    # Run the formatter
    - id: ruff-format
      types_or: [python, pyi]
      args: ['--exclude', 'tests/*']  # Skip the tests directory
