repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.5  # Ruff version.
  hooks:
    - id: ruff-check  # Run the linter
      types_or: [python, pyi]
      args: [src/aplustools, --fix, --quiet]
    - id: ruff-format  # Run the formatter
      types_or: [python, pyi]
      args: [src/aplustools]
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
