repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.3  # Ruff version.
  hooks:
    - id: ruff-check  # Run the linter
      types_or: [python, pyi]
      args: [--fix, '--exclude', 'tests/*', '--exclude', 'scripts/*', '--quiet']
    - id: ruff-format  # Run the formatter
      types_or: [python, pyi]
      args: ['--exclude', 'tests/*', '--exclude', 'scripts/*', '--quiet']
- repo: local
  hooks:
    - id: generate-docs
      name: Auto-generate API documentation
      entry: bash -c 'PYTHONPATH=src pdoc aplustools --output-dir docs'
      language: system
      pass_filenames: false
      always_run: true
      additional_dependencies: [pdoc]
      stages: [pre-commit, manual]
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
