# .pre-commit-config.yaml
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.12.3
  hooks:
    - id: ruff
      args: ['--fix']  # Automatically fix any issues
      language_version: python3
