name: Run Pre-commit Hooks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        continue-on-error: true   # This will allow the job to continue even if Ruff fails

      - name: Push formatting changes
        if: success()  # Only run if previous step was successful
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git pull --ff-only
          
          git commit -am "Apply Ruff formatting" && git push
