name: Publish Markdown Docs to Wiki

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-markdown-builder myst-parser

      - name: Build markdown docs
        run: |
          sphinx-build -b markdown docs/source docs/build/markdown

      - name: Push docs to GitHub Wiki
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone the Wiki repo
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

          # Clear existing wiki content
          rm -rf wiki/*
          
          # Copy generated markdown docs
          cp -r docs/build/markdown/* wiki/

          cd wiki
          git add .
          git commit -m "📚 Update wiki docs"
          git push
