"""BLAKE2"""

from ..._definitions import _HASHER_WITH_LEN_BACKEND

BLAKE2b: _HASHER_WITH_LEN_BACKEND = _HASHER_WITH_LEN_BACKEND("blake2b")
BLAKE2s: _HASHER_WITH_LEN_BACKEND = _HASHER_WITH_LEN_BACKEND("blake2s")
